### ISSUE TITLE
Animation in Fauna

### ISSUE THREAD

**Issue by jqliu09** [3DAnimals/3DAnimals#16]
Hi! Thanks for presenting such good work! 
I am trying to  run the animation part of Fauna, however, I firstly encountered this error:

[2024-12-11 01:59:11,975][py.warnings][WARNING] - /xxxxx/anaconda3/envs/3danimals/lib/python3.9/site-packages/torch/nn/functional.py:4003: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(

  0%|                                                  | 0/1052 [00:00<?, ?it/s]
Error executing job with overrides: []
Traceback (most recent call last):
  File "/xxxxx/code/animal/3DAnimals/visualization/visualize_results_fauna.py", line 509, in main
    _ = model.render(["shaded"], posed_shape, texture_pred, mvp_arti, w2c_arti, campos_arti, resolution,
  File "/data/jiaqi.liu/code/animal/3DAnimals/model/models/AnimalModel.py", line 209, in render
    rendered = render.render_mesh(
  File "/xxxxx/code/animal/3DAnimals/model/render/render.py", line 281, in render_mesh
    rendered = render_layer(rast, db, mesh, w2c, view_pos, material, lgt, resolution, spp, msaa, bsdf, feat=feat, render_modes=render_modes, prior_mesh=prior_mesh, two_sided_shading=two_sided_shading, delta_xy=delta_xy, dino_net=dino_net, class_vector=class_vector)
  File "/xxxxx/code/animal/3DAnimals/model/render/render.py", line 196, in render_layer
    buffers = shade(gb_pos, gb_geometric_normal, gb_normal, gb_tangent, gb_tex_pos, w2c, view_pos, lgt, material, bsdf, feat=feat, render_modes=render_modes, two_sided_shading=two_sided_shading, delta_xy_interp=delta_xy_interp, dino_net=dino_net, class_vector=class_vector)
  File "/xxxxx/code/animal/3DAnimals/model/render/render.py", line 61, in shade
    dino_pred = dino_net.sample(gb_tex_pos, feat=class_vector)
  File "/xxxxx/code/animal/3DAnimals/model/networks/MLPs.py", line 101, in sample
    return self.forward(x, feat)
  File "/xxxxx/code/animal/3DAnimals/model/networks/MLPs.py", line 93, in forward
    feat = feat.expand(*x_in.shape[:-1], -1)
RuntimeError: The expanded size of the tensor (1) must match the existing size (51) at non-singleton dimension 0.  Target sizes: [1, 256, 256, -1].  Tensor sizes: [51, 1, 1, 128]

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I assume the error is caused by the wrong batch size, so I modified the num_frames to 1 and rerun. But the results is not correct:

https://github.com/user-attachments/assets/60fc08a1-2a3d-414c-b9e4-950d52b1ae93

I can successfully visualize the rotate results and other_view results, 

https://github.com/user-attachments/assets/eba62850-1b87-4199-859a-d6c6f687f0dc

Could I ask for your help if there are any ideas for such error?

**Comment by kyleleey** [comment]
Hi @jqliu09 

Thanks for letting us know, we just updated the main branch to fix the problems you mentioned.

1. In previous visualize_results_fauna.py, the variable num_frames has been mistakenly assigned twice, causing the shape error. Now it should be fine and no need to manually reset the num_frames.

2. Previously the loaded articulation parameters weren't transformed into radian values correctly, now it should be fine.

Please let us know if you encounter other problems!

**Comment by kyleleey** [comment]
Hi @jqliu09 

1. If I understand your question correctly, the pose.txt contains the pose output from self.netInstance, which means the predicted viewpoint camera pose, which is different from articulation parameters.
2. The visualization script is using a pre-defined animation sequence on any shape predictions and render this animation visualization video. It won't use texture or shape predictions from other images. I think the low quality here is because you didn't turn on the test-time optimization, which can provide better texture alignment with the input image.
3. You can save the articulation parameter from one image and use that on the prediction of another animal image, which should be similar to what we're doing in the "animation" part in the visualize_results_fauna.py script.

**Comment by jqliu09** [comment]
> Hi @jqliu09
> 
> 1. If I understand your question correctly, the pose.txt contains the pose output from self.netInstance, which means the predicted viewpoint camera pose, which is different from articulation parameters.
> 2. The visualization script is using a pre-defined animation sequence on any shape predictions and render this animation visualization video. It won't use texture or shape predictions from other images. I think the low quality here is because you didn't turn on the test-time optimization, which can provide better texture alignment with the input image.
> 3. You can save the articulation parameter from one image and use that on the prediction of another animal image, which should be similar to what we're doing in the "animation" part in the visualize_results_fauna.py script.

Thx a lot ! It is clearly solve my question !
